"""add yield_percent and ingredient unit conversions

Revision ID: 052e7c2b8d43
Revises: aabc5feddd14
Create Date: 2026-08-27 04:03:34.766617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '052e7c2b8d43'
down_revision: Union[str, None] = 'aabc5feddd14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_unit_conversions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('to_base_qty', sa.Numeric(precision=14, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['cobi_kerupuk.ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.add_column('ingredients', sa.Column('yield_percent', sa.Numeric(precision=5, scale=2), nullable=False, server_default=sa.text('100.00')), schema='cobi_kerupuk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'yield_percent', schema='cobi_kerupuk')
    op.drop_table('ingredient_unit_conversions', schema='cobi_kerupuk')
    # ### end Alembic commands ###
