"""init schema

Revision ID: 13e83b181e25
Revises: 
Create Date: 2026-08-19 08:12:48.355709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13e83b181e25'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='cobi_kerupuk'
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('businesses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    schema='core'
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='core'
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('contact', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('ingredient_price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['cobi_kerupuk.ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('variant_label', sa.String(length=150), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('min_stock_qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_unit', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cobi_kerupuk.product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['core.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='core'
    )
    op.create_table('procurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('price_mode', sa.String(length=20), nullable=False),
    sa.Column('bonus_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['inventory.clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('vendor_item_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['inventory.items.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['inventory.vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('recipes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['cobi_kerupuk.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['cobi_kerupuk.products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['cobi_kerupuk.sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reason', sa.String(length=150), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['cobi_kerupuk.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('procurement_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('procurement_id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('vendor_id', sa.Integer(), nullable=True),
    sa.Column('spec', sa.String(length=255), nullable=True),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('client_price', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('client_price_locked', sa.Boolean(), nullable=False),
    sa.Column('vendor_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('margin_override', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['inventory.items.id'], ),
    sa.ForeignKeyConstraint(['procurement_id'], ['inventory.procurements.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['inventory.vendors.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='inventory'
    )
    op.create_table('recipe_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('total_cogs_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('effective_from', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['cobi_kerupuk.recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('recipe_version_ingredients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipe_version_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('unit_price_snapshot', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['cobi_kerupuk.ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['cobi_kerupuk.recipe_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_version_ingredients', schema='cobi_kerupuk')
    op.drop_table('recipe_versions', schema='cobi_kerupuk')
    op.drop_table('procurement_items', schema='inventory')
    op.drop_table('stock_movements', schema='cobi_kerupuk')
    op.drop_table('sale_items', schema='cobi_kerupuk')
    op.drop_table('recipes', schema='cobi_kerupuk')
    op.drop_table('vendor_item_prices', schema='inventory')
    op.drop_table('procurements', schema='inventory')
    op.drop_table('users', schema='core')
    op.drop_table('products', schema='cobi_kerupuk')
    op.drop_table('ingredient_price_history', schema='cobi_kerupuk')
    op.drop_table('vendors', schema='inventory')
    op.drop_table('items', schema='inventory')
    op.drop_table('clients', schema='inventory')
    op.drop_table('roles', schema='core')
    op.drop_table('businesses', schema='core')
    op.drop_table('sales', schema='cobi_kerupuk')
    op.drop_table('product_categories', schema='cobi_kerupuk')
    op.drop_table('ingredients', schema='cobi_kerupuk')
    # ### end Alembic commands ###
