"""add customer, sales order, payment

Revision ID: 1fbb73e8ac40
Revises: 052e7c2b8d43
Create Date: 2026-08-29 13:16:12.995383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1fbb73e8ac40'
down_revision: Union[str, None] = '052e7c2b8d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('sales_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('shipping_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['cobi_kerupuk.customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('method', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['cobi_kerupuk.sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('sales_order_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['cobi_kerupuk.sales_orders.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['cobi_kerupuk.products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sales_order_items', schema='cobi_kerupuk')
    op.drop_table('payments', schema='cobi_kerupuk')
    op.drop_table('sales_orders', schema='cobi_kerupuk')
    op.drop_table('customers', schema='cobi_kerupuk')
    # ### end Alembic commands ###
