"""add size_label and bulk product create

Revision ID: 265393691d1e
Revises: cab25b704978
Create Date: 2026-08-23 04:06:09.167248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '265393691d1e'
down_revision: Union[str, None] = 'cab25b704978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('size_label', sa.String(length=100), nullable=True), schema='cobi_kerupuk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'size_label', schema='cobi_kerupuk')
    # ### end Alembic commands ###
