"""add purchase history and monthly overhead

Revision ID: 2c0b7fdb2408
Revises: 7bb74daf62b8
Create Date: 2026-08-25 02:58:54.996433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2c0b7fdb2408'
down_revision: Union[str, None] = '7bb74daf62b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monthly_overheads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('estimated_production_grams', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.create_table('overhead_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monthly_overhead_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['monthly_overhead_id'], ['cobi_kerupuk.monthly_overheads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.add_column('ingredient_price_history', sa.Column('purchase_qty', sa.Numeric(precision=14, scale=3), nullable=True), schema='cobi_kerupuk')
    op.add_column('ingredient_price_history', sa.Column('purchase_unit', sa.String(length=20), nullable=True), schema='cobi_kerupuk')
    op.add_column('ingredient_price_history', sa.Column('total_price', sa.Numeric(precision=14, scale=2), nullable=True), schema='cobi_kerupuk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredient_price_history', 'total_price', schema='cobi_kerupuk')
    op.drop_column('ingredient_price_history', 'purchase_unit', schema='cobi_kerupuk')
    op.drop_column('ingredient_price_history', 'purchase_qty', schema='cobi_kerupuk')
    op.drop_table('overhead_items', schema='cobi_kerupuk')
    op.drop_table('monthly_overheads', schema='cobi_kerupuk')
    # ### end Alembic commands ###
