"""restructure recipe to per-level with scaling

Revision ID: 7bb74daf62b8
Revises: 8ef3370daed2
Create Date: 2026-08-24 10:47:13.748333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7bb74daf62b8'
down_revision: Union[str, None] = '8ef3370daed2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('base_yield_grams', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('active_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.add_column('products', sa.Column('weight_grams', sa.Numeric(precision=10, scale=2), nullable=True), schema='cobi_kerupuk')
    op.add_column('products', sa.Column('recipe_group_id', sa.Integer(), nullable=True), schema='cobi_kerupuk')
    op.create_foreign_key(None, 'products', 'recipe_groups', ['recipe_group_id'], ['id'], source_schema='cobi_kerupuk', referent_schema='cobi_kerupuk')
    op.add_column('recipe_versions', sa.Column('recipe_group_id', sa.Integer(), nullable=False), schema='cobi_kerupuk')
    op.drop_constraint('recipe_versions_recipe_id_fkey', 'recipe_versions', schema='cobi_kerupuk', type_='foreignkey')
    op.create_foreign_key(None, 'recipe_versions', 'recipe_groups', ['recipe_group_id'], ['id'], source_schema='cobi_kerupuk', referent_schema='cobi_kerupuk')
    op.drop_column('recipe_versions', 'recipe_id', schema='cobi_kerupuk')
    op.drop_table('recipes', schema='cobi_kerupuk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe_versions', sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False), schema='cobi_kerupuk')
    op.drop_constraint(None, 'recipe_versions', schema='cobi_kerupuk', type_='foreignkey')
    op.create_foreign_key('recipe_versions_recipe_id_fkey', 'recipe_versions', 'recipes', ['recipe_id'], ['id'], source_schema='cobi_kerupuk', referent_schema='cobi_kerupuk')
    op.drop_column('recipe_versions', 'recipe_group_id', schema='cobi_kerupuk')
    op.drop_constraint(None, 'products', schema='cobi_kerupuk', type_='foreignkey')
    op.drop_column('products', 'recipe_group_id', schema='cobi_kerupuk')
    op.drop_column('products', 'weight_grams', schema='cobi_kerupuk')
    op.create_table('recipes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('active_version_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['cobi_kerupuk.products.id'], name='recipes_product_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='recipes_pkey'),
    schema='cobi_kerupuk'
    )
    op.drop_table('recipe_groups', schema='cobi_kerupuk')
    # ### end Alembic commands ###
