"""add is_active to category, product update/delete

Revision ID: 8ef3370daed2
Revises: 265393691d1e
Create Date: 2026-08-23 04:39:02.026931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ef3370daed2'
down_revision: Union[str, None] = '265393691d1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'product_categories',
        sa.Column('is_active', sa.Boolean(), nullable=True),
        schema='cobi_kerupuk',
    )
    op.execute(
        "UPDATE cobi_kerupuk.product_categories SET is_active = TRUE WHERE is_active IS NULL"
    )
    op.alter_column(
        'product_categories',
        'is_active',
        existing_type=sa.Boolean(),
        nullable=False,
        schema='cobi_kerupuk',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product_categories', 'is_active', schema='cobi_kerupuk')
    # ### end Alembic commands ###
