"""add brand to purchase history, is_active to ingredient

Revision ID: a8b36364264b
Revises: 2c0b7fdb2408
Create Date: 2026-08-26 05:11:02.624792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a8b36364264b'
down_revision: Union[str, None] = '2c0b7fdb2408'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredient_price_history', sa.Column('brand', sa.String(length=100), nullable=True), schema='cobi_kerupuk')
    # Add `is_active` with a server default so existing rows get a non-null value.
    op.add_column(
        'ingredients',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('true'),
        ),
        schema='cobi_kerupuk',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'is_active', schema='cobi_kerupuk')
    op.drop_column('ingredient_price_history', 'brand', schema='cobi_kerupuk')
    # ### end Alembic commands ###
