"""add is_active to monthly overhead

Revision ID: aabc5feddd14
Revises: b2e8b7b02758
Create Date: 2026-08-27 03:22:06.984536

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "aabc5feddd14"
down_revision: Union[str, None] = "b2e8b7b02758"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "monthly_overheads",
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, server_default=sa.text("true")
        ),
        schema="cobi_kerupuk",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monthly_overheads", "is_active", schema="cobi_kerupuk")
    # ### end Alembic commands ###
