"""add is_active to recipe_group

Revision ID: b2e8b7b02758
Revises: a8b36364264b
Create Date: 2026-08-27 02:52:58.909319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b2e8b7b02758'
down_revision: Union[str, None] = 'a8b36364264b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add `is_active` with a server default so existing rows get a non-null value.
    op.add_column(
        'recipe_groups',
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('true')),
        schema='cobi_kerupuk',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe_groups', 'is_active', schema='cobi_kerupuk')
    # ### end Alembic commands ###
