"""add ingredient stock tracking

Revision ID: bc47167a4281
Revises: f3a1c9d7e2b4
Create Date: 2026-08-31 09:50:12.269204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bc47167a4281'
down_revision: Union[str, None] = 'f3a1c9d7e2b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient_stock_adjustments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.Column('qty_before', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('qty_after', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['cobi_kerupuk.ingredients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.add_column(
        'ingredients',
        sa.Column(
            'stock_qty',
            sa.Numeric(precision=14, scale=3),
            nullable=False,
            server_default=sa.text('0'),
        ),
        schema='cobi_kerupuk',
    )
    op.add_column(
        'ingredients',
        sa.Column(
            'min_stock_qty',
            sa.Numeric(precision=14, scale=3),
            nullable=False,
            server_default=sa.text('0'),
        ),
        schema='cobi_kerupuk',
    )
    op.add_column(
        'ingredients',
        sa.Column(
            'lead_time_days',
            sa.Integer(),
            nullable=False,
            server_default=sa.text('0'),
        ),
        schema='cobi_kerupuk',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'lead_time_days', schema='cobi_kerupuk')
    op.drop_column('ingredients', 'min_stock_qty', schema='cobi_kerupuk')
    op.drop_column('ingredients', 'stock_qty', schema='cobi_kerupuk')
    op.drop_table('ingredient_stock_adjustments', schema='cobi_kerupuk')
    # ### end Alembic commands ###
