"""add discount, order date, status log

Revision ID: c0f7a8b6f7bd
Revises: merge_1fbb_d1a2
Create Date: 2026-08-30 08:38:07.924436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'c0f7a8b6f7bd'
down_revision: Union[str, None] = 'merge_1fbb_d1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_status_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['cobi_kerupuk.sales_orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='cobi_kerupuk'
    )
    op.add_column('sales_order_items', sa.Column('discount_type', sa.String(length=10), nullable=False), schema='cobi_kerupuk')
    op.add_column('sales_order_items', sa.Column('discount_value', sa.Numeric(precision=14, scale=2), nullable=False), schema='cobi_kerupuk')
    op.alter_column('sales_orders', 'order_date',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.Date(),
               existing_nullable=False,
               schema='cobi_kerupuk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sales_orders', 'order_date',
               existing_type=sa.Date(),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               schema='cobi_kerupuk')
    op.drop_column('sales_order_items', 'discount_value', schema='cobi_kerupuk')
    op.drop_column('sales_order_items', 'discount_type', schema='cobi_kerupuk')
    op.drop_table('order_status_logs', schema='cobi_kerupuk')
    # ### end Alembic commands ###
