"""no-op check

Revision ID: cab25b704978
Revises: 13e83b181e25
Create Date: 2026-08-19 13:49:08.024787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'cab25b704978'
down_revision: Union[str, None] = '13e83b181e25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
